//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnAppleADay_03
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnAppleADay_01Entities : DbContext
    {
        public AnAppleADay_01Entities()
            : base("name=AnAppleADay_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeachersBlog> TeachersBlogs { get; set; }
        public virtual DbSet<TeachersWishlist> TeachersWishlists { get; set; }
    }
}
