//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnAppleADay_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersBlog
    {
        public int postId { get; set; }
        public string teachId { get; set; }
        public string post { get; set; }
        public System.DateTime publishDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
